Fix/리뷰 이미지 파일 중복, 별점 평균 오류 수정
Step3-kakao-tech-campus/Team6_BE pull request #69
Opened 2023-11-06 17:36 UTC by enchantee00

## 수행한 일
- 리뷰 업데이트 시 이미지 파일 중복으로 뜨는 오류 해결
- 별점 평균 오류

## 전하고 싶은 말
- 별점 평균을 반올림하려고 Math.round()를 썼는데 이게 반환자가 double 타입이어서 averageRating 타입을 double로 변경했습니다!
- 별점 평균 내는 과정을 따로 메소드 빼려고 해봤는데 각자 계산하는 방식이 다 달라서,,, 빼도 코드 가독성이 좋아지는지 잘 모르겠어서 일단은 안만들었습니다! 혹시 그래도 빼는게 좋다고 생각하시면 빼겠습니다!

2023-11-07 05:01 UTC, zigimi approved these changes

2023-11-07 08:42 UTC, JJimini requested changes
저도 한 번 test 해보겠습니다

2023-11-07 10:31 UTC, JJimini reviewed
제가 이미지 삭제에 대해 테스트 해본 내역입니다!
- 이미지 파일이 없는 리뷰인 경우 deleteImage의 "삭제할 이미지가 없습니다"에 걸려서 리뷰 삭제 불가능
- 별점 상한이 없는 것 같습니다. 별점을 6.0으로 해도 그대로 들어가네요...?
- 리뷰가 1개였는데 0개가 되는 경우에 대한 예외처리가 필요해보입니다.
- 추가적으로 별점은 update가 잘 되던가요?? 
    - postman확인할 경우, 리뷰 생성 했을 때 별점과 리뷰 삭제 했을 때 별점이 달라야 합니다.

2023-11-08 13:39 UTC, JJimini approved these changes
제가 코드 확인 못할 수도 있을 것 같아서 미리 Approve 해두겠습니당!

2023-11-09 03:35 UTC, merged